### PR TITLE
Use one line statement instead of the for of

### PR DESCRIPTION
**Pull request by saadshahd**

### CODE REVIEW

**Comment by sindresorhus** [comment]
You're confusing [iterables and iterators](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Iteration_protocols).

It could have been:

``` js
module.exports = iterable => iterable[Symbol.iterator]().next().done;
```

But I think the current is clearer.

**Comment by schnittstabil** [comment]
That's not the same. A one liner would be:

``` js
return iterable[Symbol.iterator]().next().done;
```

See the [specs](http://www.ecma-international.org/ecma-262/6.0/#sec-iterable-interface) or [MDN](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Iteration_protocols) for details.

**Comment by sindresorhus** [comment]
@schnittstabil Lol. Too slow :p

**Comment by saadshahd** [comment]
Ooops, sorry!

**Comment by saadshahd** [comment]
Hey @sindresorhus,
`!Array.from(iterable).length` will make a needless conversion. so you avoid it, right?

**Comment by sindresorhus** [comment]
Yes

**Pull request closed without merging**
